### ISSUE TITLE
Replace emojis instead of blocking render

### ISSUE THREAD

**Issue by jeannen** [nuxt-modules/og-image#187]
Hey!

Seems like there is an issue with the twemoji module used to generate images from emojis.

Maxcdn , the CDN used to fetch the images is offline. https://github.com/twitter/twemoji/issues/580 
Anytime an emoji is used in the OG image title or description it crashes it (error below)

I'm not sure if MaxCDN being offline is permanent or just a bug, but it would be nice to ignore emojis if it blocks render, else it's impossible to deploy the app without disabling OG-Images

```
 ERROR  Can't load image https://twemoji.maxcdn.com/v/14.0.2/svg/1f44b.svg: fetch failed                                                                          9:55:04 AM

  ├─ /blog/my-journey/__og_image__/og.png (7728ms)                                                                                                          nitro 9:55:04 AM
  │ ├── Error: [500] Failed to create og image: Image size cannot be determined. Please provide the width and height of the image.
  │ └── Linked from /blog/my-journey
```

**Comment by harlan-zw** [comment]
Hey, can you make sure you're using [v3](https://nuxtseo.com/og-image/releases/v3)?

**Comment by jeannen** [comment]
> Hey, can you make sure you're using [v3](https://nuxtseo.com/og-image/releases/v3)? We no longer use the `twemoji` package

It works but it generate a new issue now, seems like it require a NPM auth token? I can't deploy on Cloudflare pages anymore
The issue stops if I roll back to previous version or uninstall nuxt-og images

```
18:59:47.843	Installing project dependencies: npm clean-install --progress=false
19:00:01.577	npm ERR! code E401
19:00:01.585	npm ERR! Incorrect or missing password.
19:00:01.587	npm ERR! If you were trying to login, change your password, create an
19:00:01.593	npm ERR! authentication token or enable two-factor authentication then
19:00:01.598	npm ERR! that means you likely typed your password in incorrectly.
19:00:01.599	npm ERR! Please try again, or recover your password at:
19:00:01.599	npm ERR!     https://www.npmjs.com/forgot
19:00:01.599	npm ERR! 
19:00:01.599	npm ERR! If you were doing some other operation then your saved credentials are
19:00:01.599	npm ERR! probably out of date. To correct this please try logging in again with:
19:00:01.599	npm ERR!     npm login
19:00:01.600	
19:00:01.605	npm ERR! A complete log of this run can be found in: /opt/buildhome/.npm/_logs/2024-04-10T09_59_48_545Z-debug-0.log
19:00:01.623	Error: Exit with error code: 1
19:00:01.628	    at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
19:00:01.631	    at Object.onceWrapper (node:events:652:26)
19:00:01.633	    at ChildProcess.emit (node:events:537:28)
19:00:01.636	    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
19:00:01.641	Failed: build command exited with code: 1
19:00:08.458	Failed: error occurred while running build command
```

**Comment by jeannen** [comment]
@harlan-zw any chance you had a look at this? 👀
Still can't deploy anything that includes the new version

**Comment by harlan-zw** [comment]
This does not seem related to the module, you should be using version `3.0.0-rc.52` if you want to use the latest v3.

If you're using this please paste the complete log and / or make a reproduction. I don't think you'll be able to though as StackBlitz demo works (https://stackblitz.com/edit/nuxt-starter-pxs3wk?file=pages/index.vue) and https://github.com/harlan-zw/nuxt-og-image-playground deploys on Cloudflare without issue :thinking:

**Comment by cossssmin** [comment]
This continues to happen in latest v5.0.3, build fails on Cloudlfare because some SVG icon cannot be fetched from an external source. Why does it try to fetch `https://api.iconify.design/noto/high-voltage.svg` and is there any way to disable this in production please?

```sh
16:30:38.535 | [error] [request error] [unhandled] [GET] http://localhost/__og-image__/static/starters/amp4email/og.png
-- | --
16:30:38.535 | [GET] "https://api.iconify.design/noto/high-voltage.svg": <no response> fetch failed
16:30:38.535 | at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
16:30:38.536 | at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:270:14)
16:30:38.536 | at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
16:30:38.536 | at async .nuxt/prerender/chunks/_/emojis.mjs:3609:15
16:30:38.536 | at async Promise.all (index 0)
16:30:38.536 | at async applyEmojis (.nuxt/prerender/chunks/_/emojis.mjs:3600:24)
16:30:38.537 | at async createVNodes (.nuxt/prerender/chunks/_/renderer.mjs:370:5)
16:30:38.537 | at async Promise.all (index 1)
16:30:38.537 | at async createSvg (.nuxt/prerender/chunks/_/renderer.mjs:422:35)
16:30:38.537 | at async createPng (.nuxt/prerender/chunks/_/renderer.mjs:441:15)
16:30:38.537 |  
16:30:38.537 | [cause]: fetch failed
16:30:38.537 | at node:internal/deps/undici/undici:13185:13
16:30:38.538 | at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
16:30:38.538 | at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:258:26)
16:30:38.538 | at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:270:14)
16:30:38.538 | at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
16:30:38.538 | at async .nuxt/prerender/chunks/_/emojis.mjs:3609:15
16:30:38.538 | at async Promise.all (index 0)
16:30:38.538 | at async applyEmojis (.nuxt/prerender/chunks/_/emojis.mjs:3600:24)
16:30:38.538 | at async createVNodes (.nuxt/prerender/chunks/_/renderer.mjs:370:5)
16:30:38.539 | at async Promise.all (index 1)
16:30:38.539 |  
16:30:38.539 | [cause]:
16:30:38.539 | [log] [nitro]   ├─ /__og-image__/static/templates/ce-essential-transactional/og.png (8172ms)
16:30:38.539 | at internalConnectMultiple (node:net:1117:18)
16:30:38.539 | at internalConnectMultiple (node:net:1185:5)
16:30:38.540 | at Timeout.internalConnectMultipleTimeout (node:net:1711:5)
16:30:38.540 | at listOnTimeout (node:internal/timers:596:11)
16:30:38.540 | at process.processTimers (node:internal/timers:529:7)
```

**Comment by harlan-zw** [comment]
The fetching should be more stable now, I'm happy to support non-api usage but will be a little bit of an effort so a new issue just for that would be useful
