### ISSUE TITLE
NuxtSeo not working after installation

### ISSUE THREAD

**Issue by azharumar** [nuxt-modules/og-image#204]
After installation, and as per documentation, I put this `defineOgImageComponent('NuxtSeo')` in index.vue, but I get this error in nuxt dev console.
Error: [GET] "/__og-image__/image/og.json": 500 [Nuxt OG Image] Failed to read the path / for og-image extraction. [GET] "/": 500 .

![image](https://github.com/nuxt-modules/og-image/assets/19702561/f0c48fb4-58cc-4ebf-bf8f-19f78c8b5670)

**Comment by harlan-zw** [comment]
Hi, could you try accessing this URL directly and see if you can get the stacktrace?

It's possibly related to some middleware you have

**Comment by Ismael-Rakotondrazaka** [comment]
Hi,
I have the same issue.
This is what I get when accessing directly the url
```
500
[Nuxt OG Image] Failed to read the path / for og-image extraction. [GET] "/": 500 .

at fetchPathHtmlAndExtractOptions (C:\Users\Ismael\Workspace\remake\nuxt-3-template\node_modules\nuxt-og-image\dist\runtime\nitro\og-image\context.mjs:157:12)
at resolveContext (C:\Users\Ismael\Workspace\remake\nuxt-3-template\node_modules\nuxt-og-image\dist\runtime\nitro\og-image\context.mjs:55:23)
at Object.handler (C:\Users\Ismael\Workspace\remake\nuxt-3-template\node_modules\nuxt-og-image\dist\runtime\nitro\routes\image.mjs:7:15)
at async /C:/Users/Ismael/Workspace/remake/nuxt-3-template/node_modules/h3/dist/index.mjs:1962:19
at async Object.callAsync (/C:/Users/Ismael/Workspace/remake/nuxt-3-template/node_modules/unctx/dist/index.mjs:72:16)
at async Object.callAsync (/C:/Users/Ismael/Workspace/remake/nuxt-3-template/node_modules/unctx/dist/index.mjs:72:16)
at async Server.toNodeHandle (/C:/Users/Ismael/Workspace/remake/nuxt-3-template/node_modules/h3/dist/index.mjs:2249:7)
```

**Comment by ptdev** [comment]
Hi,

Sorry for adding to a closed ticket, but I'm also getting some of these strange issues and have some more feedback that may be useful

Sometimes we get error 500, other times we get error 404. Most of the times, this happens only when navigating.

Even when we get errors, the og-image is still generated and shown most of the times, but occasionally we also get the same white page with the error as the OP's screenshot.

I've figured out that this only happens in dev mode and with the nuxt developer tools enabled so I'm guessing it's some issue with the devtools og-image tab and not with our own code.

Disabling devtools or in production mode the errors do not happen.

Let me know if you need any more feedback.

Cheers.

**Comment by devstack-be** [comment]
I m facing the same issue:

500
[Nuxt OG Image] Failed to read the path /docs/getting-started for og-image extraction. [GET] "/docs/getting-started": 404 Not Found.

at fetchPathHtmlAndExtractOptions (./node_modules/.pnpm/nuxt-og-image@3.0.0-rc.60_@lezer+common@1.2.1_@nuxt+devtools@1.3.6_rollup@4.18.0_vite@5.3.1_@_fszjgh5curctvxpwiqqc3jch34/node_modules/nuxt-og-image/dist/runtime/nitro/og-image/context.js:162:12)
at resolveContext (./node_modules/.pnpm/nuxt-og-image@3.0.0-rc.60_@lezer+common@1.2.1_@nuxt+devtools@1.3.6_rollup@4.18.0_vite@5.3.1_@_fszjgh5curctvxpwiqqc3jch34/node_modules/nuxt-og-image/dist/runtime/nitro/og-image/context.js:56:23)
at Object.handler (./node_modules/.pnpm/nuxt-og-image@3.0.0-rc.60_@lezer+common@1.2.1_@nuxt+devtools@1.3.6_rollup@4.18.0_vite@5.3.1_@_fszjgh5curctvxpwiqqc3jch34/node_modules/nuxt-og-image/dist/runtime/nitro/routes/image.js:7:15)
at async ./node_modules/h3/dist/index.mjs:1975:19
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2266:7)

**Comment by vasilistotskas** [comment]
I also have same issue
