### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by moshetanzer** [nuxt-modules/og-image#244]
Hi @harlan-zw,

Hope you keeping well!

Have come across the following error
```
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading '1')
  at matcher (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:343:30)  
  at matchListing (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:278:20)  
  at callback (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:328:16)  
  at matchCall (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:156:20)  
  at matchRGBColor (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:325:12)  
  at matchColor (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:311:7)  
  at matcher (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:297:17)  
  at matchListing (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:278:20)  
  at callback (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:144:21)  
  at a (./node_modules/.pnpm/satori@0.10.14/node_modules/satori/src/vendor/gradient-parser/index.js:156:20)

```
when using the following gradient
```

 <div class="absolute inset-0 landing-grid z-[-1] [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]" />

.landing-grid {
  background-size: 100px 100px;
  background-image:
    linear-gradient(to right, rgb(var(--color-gray-200)) 1px, transparent 1px),
    linear-gradient(to bottom, rgb(var(--color-gray-200)) 1px, transparent 1px);
}
.dark {
  .landing-grid {
    background-image:
      linear-gradient(to right, rgb(var(--color-gray-800)) 1px, transparent 1px),
      linear-gradient(to bottom, rgb(var(--color-gray-800)) 1px, transparent 1px);
  }
}
```

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. Unfortunately, this is a bug in [Satori](https://github.com/vercel/satori) which I don't have any capacity to investigate.

I'd suggest exporting the gradient as an SVG and using that directly as a work around, otherwise please make an issue on the Satori repo using their reproduction guidelines.
