### ISSUE TITLE
ReSVG rust package throwing error

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/og-image#265]
### 🐛 The bug

When working on og images often I run into everything crashing so the DevTools are no more accessible and reloading the page does no better. This means while composing og images (which is not easy due to limitations of Satori) I need to restart the Nuxt dev process over and over again. Sometimes I make changes, restart Nuxt, make change, restart Nuxt, and so on ...

I would be nice if when something crashes not the whole DevTools go down and I could reload the page and everything is fine again or (better) after a file change everything works again.

For example, if I just place three images `<img src="/images/1.jpg" />` that are 1500px wide each, everything crashes:

```
thread '<unnamed>' panicked at /Users/runner/.cargo/git/checkouts/resvg-4b7e4ee32ad6d954/3495d87/crates/resvg/src/geom.rs:27:61:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

 ERROR  [unhandledRejection] socket hang up 
 at Socket.socketOnEnd (node:_http_client:516:23)
 at Socket.emit (node:events:531:35)
 at endReadableNT (node:internal/streams/readable:1696:12)
 at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

![Image](https://github.com/user-attachments/assets/2eac7b9a-a13e-4b8a-b5e0-bf247736e4ab)

### 🛠️ To reproduce

-

### 🌈 Expected behavior

Catch errors and keep the process alive

**Comment by MickL** [comment]
I upgrade to 3.x, seems to no be crashing anymore

**Comment by harlan-zw** [comment]
This seems to be an issue with the ReSVG wasm crashing the node instance, are you able to provide a reproduction?

It may come down to a Node version or OS issue.

**Comment by PGimenez** [comment]
I'm having the same issue when building a static Nuxt site. It crashes with this error

```
thread '<unnamed>' panicked at /Users/runner/.cargo/git/checkouts/resvg-4b7e4ee32ad6d954/3495d87/crates/resvg/src/geom.rs:27:61:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x11fcfc584 - _napi_register_module_v1
   1:        0x11fba53e8 - <unknown>
   2:        0x11fcdc15c - _napi_register_module_v1
   3:        0x11fcfde18 - _napi_register_module_v1
   4:        0x11fcfd5f8 - _napi_register_module_v1
   5:        0x11fcfe65c - _napi_register_module_v1
   6:        0x11fcfe0fc - _napi_register_module_v1
   7:        0x11fcfe08c - _napi_register_module_v1
   8:        0x11fcfe080 - _napi_register_module_v1
   9:        0x11fdcf6d0 - _napi_register_module_v1
  10:        0x11fdcf7f8 - _napi_register_module_v1
  11:        0x11fc61d10 - _napi_register_module_v1
  12:        0x11fc64cdc - _napi_register_module_v1
  13:        0x11fc61788 - _napi_register_module_v1
  14:        0x11fc6153c - _napi_register_module_v1
  15:        0x11fc64250 - _napi_register_module_v1
  16:        0x11fc64d1c - _napi_register_module_v1
  17:        0x11fc61a30 - _napi_register_module_v1
  18:        0x11fc64cdc - _napi_register_module_v1
  19:        0x11fc61788 - _napi_register_module_v1
  20:        0x11fc6153c - _napi_register_module_v1
  21:        0x11fb8200c - <unknown>
  22:        0x11fb84cf4 - <unknown>
  23:        0x104af66bc - __ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
fatal runtime error: failed to initiate panic, error 5
[1]    61531 abort      npm run build
```

I configured nitro rendering like this

```js
nitro: {
    prerender: {
      crawlLinks: true,
      concurrency: 10,
      failOnError: false,
      static: true,
    }
  }
```

These are my system details

```
- Operating System: `Darwin`
- Node Version:     `v22.6.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

```

**Comment by KamcyAhaka** [comment]
Hi @MickL  and @PGimenez, were you both able to find a fix for this issue? I am facing the same bug currently

**Comment by zhikto** [comment]
I too faced this problem and it plagued me for a long time. If you are using nuxt-seo, it may be doing something bad: when you introduce nuxt-seo (seo utils), for some reason the description text is being poured in the ogImage template's defineProps, even though it should not be specified. (I noticed this with nuxt dev tools). And this description text, if huge, caused this error. By adjusting to the proper description size, this error no longer occurred. It is an edge case, but if the formatting design is not at fault, it might be a good idea to question the nuxt-seo settings.

**Comment by MickL** [comment]
It would be nice if it restarts when it crashes. I just recently ran often into OG Images not reachable abymore and then I had to restart Nuxt. This happens easily when having a too large image for example or using some html elements / css classes that Satori doesnt like

**Comment by harlan-zw** [comment]
So the issue is that ReSVG is throwing an exception which crashes the main thread. The fix is to use a worker for resvg, which can break without causing issues. This is a bit of effort though, so I will need to revisit it.

The easiest way to kill ReSVG seems to be large titles and descriptions so I've pushed up a simple fix for the community templates to clamp the length of titles and descriptions to 2 and 3 lines respectively.

You can implement this in your own templates like so

```html
<h1 class="text-[60px]" style="display: block; line-clamp: 2; text-overflow: ellipsis;">
  {{ title }}
</h1>
```
