### ISSUE TITLE
fix: Pre-rendering issues with unocss version 0.65

### ISSUE THREAD

**Issue by sumomo015** [nuxt-modules/og-image#288]
### 🐛 The bug

When I run `npm run generate`, the following error occurs.

```
ERROR [nuxt] [request error] [unhandled] [500] uno.parseToken is not a function 15:29:18
at Object.transform (./.nuxt/prerender/chunks/_/renderer.mjs:304:37)
at walkSatoriTree (./.nuxt/prerender/chunks/_/renderer.mjs:82:32)
at walkSatoriTree (./.nuxt/prerender/chunks/_/renderer.mjs:85:12)
at createVNodes (./.nuxt/prerender/chunks/_/renderer.mjs:391:21)
at async Promise.all (index 1)
at async createSvg (./.nuxt/prerender/chunks/_/renderer.mjs:429:35)
at async createPng (./.nuxt/prerender/chunks/_/renderer.mjs:446:15)
at async Object.imageEventHandler [as handler] (./.nuxt/prerender/chunks/_/eventHandlers.mjs:336:13)
at async Object.eval [as handler] (./node_modules/h3/dist/index.mjs:2103:19)
at async toNodeHandle (./node_modules/h3/dist/index.mjs:2395:7)

├─ /**og-image**/static/og.png (446ms) nitro 15:29:18
│ ├── [500]
│ └── Linked from /

Errors prerendering:
├─ /**og-image**/static/og.png (446ms) nitro 15:29:18
│ ├── [500]
│ └── Linked from /

ERROR Exiting due to prerender errors.

at Module.prerender (node_modules/nitropack/dist/core/index.mjs:2090:11)
at async eval (node_modules/nuxt/dist/index.mjs:3754:5)

ERROR Exiting due to prerender errors.
```

### 🛠️ To reproduce

https://stackblitz.com/edit/github-l6kxsg

### 🌈 Expected behavior

`npm run generate` runs successfully.

### ℹ️ Additional context

This issue only occurs after unocss version 0.65

Environment
```
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @unocss/nuxt@0.65.1, nuxt-og-image@4.0.0
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Thanks for the issue. Looks like UnoCSS 0.65 introduced a breaking change which I've pushed up a fix for in 4.0.1
